name: autoML-sampling-env
channels:
  - districtdatalabs
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - atomicwrites=1.4.0
  - attrs=19.3.0
  - blas=1.0
  - bokeh=2.1.1
  - brotlipy=0.7.0
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.4.1
  - colorama=0.4.3
  - cryptography=2.9.2
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask=2.19.0
  - dask-core=2.19.0
  - dask-glm=0.2.0
  - dask-ml=1.5.0
  - dbus=1.13.12
  - deap=1.3.1
  - dill=0.3.2
  - distributed=2.19.0
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.10.2
  - fsspec=0.7.4
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - heapdict=1.0.1
  - icu=58.2
  - idna=2.10
  - intel-openmp=2020.1
  - jinja2=2.11.2
  - joblib=0.15.1
  - jpeg=9b
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - llvmlite=0.33.0
  - locket=0.2.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - more-itertools=8.4.0
  - msgpack-python=1.0.0
  - multipledispatch=0.6.0
  - ncurses=6.2
  - numba=0.50.1
  - numpy=1.18.5
  - numpy-base=1.18.5
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.0.5
  - partd=1.1.0
  - pcre=8.44
  - pillow=7.1.2
  - pip=20.1.1
  - pluggy=0.13.1
  - psutil=5.7.0
  - py=1.9.0
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - pytest=5.4.3
  - pytest-runner=5.2
  - python=3.8.3
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=8.0
  - requests=2.24.0
  - scikit-learn=0.23.1
  - scikit-mdr=0.4.4
  - scipy=1.3.2
  - seaborn=0.10.1
  - setuptools=47.3.1
  - sip=4.19.13
  - six=1.15.0
  - skrebate=0.6
  - sortedcontainers=2.2.2
  - sqlite=3.32.3
  - stopit=1.1.2
  - tabulate=0.8.3
  - tbb=2020.0
  - tblib=1.6.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - tpot=0.11.5
  - tqdm=4.47.0
  - typing_extensions=3.7.4.2
  - update_checker=0.17
  - urllib3=1.25.9
  - wcwidth=0.2.5
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.2.5
  - yellowbrick=1.1
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - liac-arff==2.4.0
    - openml==0.10.2
    - pmlb==0.3
    - xgboost==1.1.1
    - xmltodict==0.12.0
